name: task_ninja
description: ""
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: ^7.9.0
  cached_network_image: ^3.3.1
  dio: ^5.4.1
  dio_smart_retry: ^6.0.0
  duration: ^3.0.13
  envied: ^0.5.3
  flash: ^3.1.0
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter

  flutter_displaymode: ^0.6.0
  flutter_form_builder: ^9.2.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.10+1
  form_builder_validators: ^9.1.0
  google_fonts: ^6.2.1
  hive_flutter: ^1.1.0
  icons_launcher: ^2.1.7
  internet_connection_checker_plus: ^2.2.0
  intl: ^0.18.1
  path_provider: ^2.1.2
  platform_info: ^4.0.2
  responsive_framework: ^1.4.0
  talker_dio_logger: ^4.0.3
  talker_flutter: ^4.0.3
  velocity_x: ^4.1.2

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8
  custom_lint: ^0.6.4
  envied_generator: ^0.5.3
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  riverpod_lint: ^2.3.10
  riverpod_test: ^0.1.4
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
